<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="ISIPLMUMLP219" failures="1" tests="7" name="Default test" time="0.071" errors="0" timestamp="2022-08-20T05:53:16 IST">
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="MobileLoginPersonalLoan" time="0.008"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="APILoginPersonalLoan" time="0.005"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="APILoginPersonalLoan4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestNGDemo.TestNGDemo.day4.APILoginPersonalLoan4(day4.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- APILoginPersonalLoan4 -->
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="MobileLoginPersonalLoan2" time="0.001"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="MobileLoginPersonalLoan1" time="0.001"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="MobileLoginPersonalLoan3" time="0.002"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="WebLoginPersonalLoan" time="0.001"/>
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="APILoginPersonalLoan2" time="0.0">
    <ignored/>
  </testcase> <!-- APILoginPersonalLoan2 -->
  <testcase classname="TestNGDemo.TestNGDemo.day4" name="APILoginPersonalLoan3" time="0.0">
    <ignored/>
  </testcase> <!-- APILoginPersonalLoan3 -->
</testsuite> <!-- Default test -->
